### ISSUE TITLE
Progress percentage undefined

### ISSUE THREAD

**Issue by charbonnier666** [DarkXaHTeP/angular-progress-http#3] opened 2017-03-10 11:05 UTC
Hi !
I try this lib but I don't have percentage on my download, it's always undefined.

here my simple code (download file works)

`public getInstallerNew = (): Observable<Response> => {
    this.headers.set('Authorization', 'Basic ' + getToken(this._router));
    return this._httpProgress.withDownloadProgressListener(progress => {
      console.log('Downloading ' + progress.percentage + '%');
    }).get(this.url + "download/app", {responseType: ResponseContentType.Blob, headers: this.headers});
  };`

console write "Downloading undefined%" about 200 times

**Comment by DarkXaHTeP** [comment] 2017-03-10 22:19
@charbonnier666 did you check lengthComputable property on the progress object? If it is false, then your server doesn't return total length of the file

**Comment by charbonnier666** [comment] 2017-03-11 10:25
@DarkXaHTeP Soon I can i check this but maybe I don't send total legth, I have a REST api (with dropwizard) but I don't remember to put any special configuration, Monday I'll write my code

**Comment by charbonnier666** [comment] 2017-03-13 08:38
@DarkXaHTeP 

> @Path("/app/download/{id}")
>     @GET
>     @Timed
>     @UnitOfWork
>     public Response downloadInstallerById(@PathParam("id") final long id) {
>         try {
>             LOGGER.info("Finding Installer by id = {}...", id);
>             // read DB app
>             Optional<AppFile> res = appFileDAO.findById(id);
>             if (res.isPresent()) {
>                 AppFile a = res.get();
>                 byte[] app = a.getApp();
>                 LOGGER.info("Found latest Installer ID= " + a.getId() + "Name= " + a.getName() + "Version= " + a.getVersion() + " Date= " + a.getDateUpdated());
>                 return Response.ok(app, MediaType.APPLICATION_OCTET_STREAM).header("Content-Disposition", "attachment; filename=\"mft-installer.zip\"").build();
>             } else
>                 return Response.serverError().build();
>         } catch (Exception e) {
>             LOGGER.error(e.getLocalizedMessage(), e);
>             return Response.serverError().build();
>         }
>     }

**Comment by DarkXaHTeP** [comment] 2017-03-13 09:15
@charbonnier666 if progressEvent.lengthComputable is false, then percent and total will always be undefined - it is a documented behavior. In your situation I would recommend trying to set Content-Length header on backend

**Comment by charbonnier666** [comment] 2017-03-13 10:21
@DarkXaHTeP Hi !
I added content-length (here headers)
`ClientResource: {Content-Type=[application/octet-stream], Content-Disposition=[attachment; filename="mft-installer.zip"], Content-Length=[41703367]}`

but I still have undefined.. :(

on frontend i have this headers:

```
HTTP/1.1 200 OK
Date: Mon, 13 Mar 2017 10:18:17 GMT
Access-Control-Allow-Origin: http://localhost:3000
Access-Control-Allow-Credentials: true
Content-Type: application/octet-stream
Content-Disposition: attachment; filename="mft-installer.zip"
Vary: Accept-Encoding
Content-Encoding: gzip
Transfer-Encoding: chunked
```

**Comment by DarkXaHTeP** [comment] 2017-03-13 19:48
@charbonnier666 I don't see Content-Length in the headers list

**Comment by charbonnier666** [comment] 2017-03-14 08:41
@DarkXaHTeP After all the day working on it I understand what doesn't works..
Dropwizard use jersey with default Transfer-Encoding as "chunked", where it's impossible to set any Content-Length, I must set this in configuration

`environment.jersey().property(ClientProperties.REQUEST_ENTITY_PROCESSING, RequestEntityProcessing.BUFFERED);`

**Comment by DarkXaHTeP** [comment] 2017-03-14 08:42
@charbonnier666 so you were able to get progress after setting Content-Length?

**Comment by charbonnier666** [comment] 2017-03-14 08:45
@DarkXaHTeP yeees 👍 :)

**Comment by DarkXaHTeP** [comment] 2017-03-14 08:45
@charbonnier666 glad to hear that. Closing the issue since the problem is resolved

**Closed as completed by DarkXaHTeP** 2017-03-14 08:45 UTC
